# Generated by Django 3.1.5 on 2021-01-24 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'post_device',
            },
        ),
        migrations.CreateModel(
            name='DeviceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.CharField(max_length=200)),
                ('temperature', models.CharField(max_length=200)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.device')),
            ],
            options={
                'db_table': 'post_devicerecord',
            },
        ),
    ]
