# Generated by Django 3.1.5 on 2021-01-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='macaddress',
            field=models.CharField(blank=True, default='nothing', max_length=200),
        ),
        migrations.AlterField(
            model_name='device',
            name='soil',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='devicerecord',
            name='humidity',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='devicerecord',
            name='temperature',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterModelTable(
            name='device',
            table=None,
        ),
        migrations.AlterModelTable(
            name='devicerecord',
            table=None,
        ),
    ]
